name: Generate Snake

permissions:
  contents: write # This grants write permission for the action to push changes.

on:
  schedule:
    # Runs everyday at midnight UTC
    - cron: "0 0 * * *"
  
  # Allows you to manually trigger the workflow from the GitHub Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Chandrasekhar152
          outputs: |
            # Output the SVG files directly into the 'dist' folder
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
          # If you want an animated GIF, you can add it here:
          # dist/github-snake.gif

      - name: Push generated files to 'output' branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output # The branch where the generated files will be pushed
          folder: dist  # The folder containing the files to deploy
          clean: true   # Deletes all existing content in the output branch before deploying
        # No need for GITHUB_TOKEN here if 'contents: write' is set at the top-level.
        # It's automatically provided when you set contents: write.
